name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes since $PREVIOUS_TAG
  $CHANGES
